// Subject Names to use

// Programming Fundamentals => PF
// Object Oriented Programming =>OOP
// Data Structures and Algorithms =>DSA
// Discrete Structures =>DS
// Operating Systems => OS
// Database Systems =>DBS
// Software Engineering=>SE
// Computer Networks=>CN
// Information Security=>IS

// Data for Links.

const mcqs = {
    mcq1: [
        {
          id:"1",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "The IETF standards documents are called ________",
          option_one: "RFC",
          option_two: "RCF",
          option_three: "ID",
          option_four: "DFC",
          answer: "A",
          explaination: "RFC stands for Request For Comments and they are documents that describe methods, behaviors, research, or innovations applicable to the working of the Internet",
        },
      ],
      mcq2: [
        {
          id:"2",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: " In the layer hierarchy as the data packet moves from the upper to the lower layers, headers are ___________",
          option_one: "Added",
          option_two: "Removed",
          option_three: "Rearranged",
          option_four: "Remain the same",
          answer: "A",
          explaination: "Each layer adds its own header to the packet from the previous layer",
        },
      ],
      mcq3: [
        {
          id:"3",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "The structure or format of data is called ___________",
          option_one: "Syntax",
          option_two: "Semantics",
          option_three: "Struct",
          option_four: "Formatting",
          answer: "A",
          explaination: "The structure and format of data are defined using syntax while Semantics defines how a particular pattern to be interpreted, and what action is to be taken based on that interpretation",
        },
      ],
      mcq4: [
        {
          id:"4",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "Communication between a computer and a keyboard involves ______________ transmission",
          option_one: "Automatic",
          option_two: "Half-duplex",
          option_three: "Full-duplex",
          option_four: "Simplex",
          answer: "D",
          explaination: "data flows in single direction",
        },
      ],
      mcq5: [
        {
          id:"5",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "The first Network was called ________",
          option_one: "CNNET",
          option_two: "NSFNET",
          option_three: "ASAPNET",
          option_four: "ARPANET",
          answer: "D",
          explaination: "ARPANET stands for Advanced Research Projects Agency Networks developed in 1969",
        },
      ],
      mcq6: [
        {
          id:"6",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "A _______ is the physical path over which a message travels.",
          option_one: "Path",
          option_two: "Medium",
          option_three: "Protocol",
          option_four: "Route",
          answer: "B",
          explaination: " Mediums can be guided (wired) or unguided (wireless).",
        },
      ],
      mcq7: [
        {
          id:"7",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "Which organization has authority over interstate and international commerce in the communications field?",
          option_one: "ITU-T",
          option_two: "iEEE",
          option_three: "FCC",
          option_four: "ISOC",
          answer: "C",
          explaination: " FCC is the abbreviation for Federal Communications Commission. founded in 1934",
        },
      ],

      mcq8: [
        {
          id:"8",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "Which of this is not a network edge device?",
          option_one: "PC",
          option_two: "SmartPhones",
          option_three: "Servers",
          option_four: "Switch",
          answer: "D",
          explaination: "Edge devices host application like browser switch donot do such",
        },
      ],
      mcq9: [
        {
          id:"9",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "A _________ set of rules that governs data",
          option_one: "Protocol",
          option_two: "Standards",
          option_three: "RFCs",
          option_four: "Servers",
          answer: "A",
          explaination: "",
        },
      ],
      mcq10: [
        {
          id:"10",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "Three or more devices share a link in ________ connection.",
          option_one: "Uniport",
          option_two: "Multiport",
          option_three: "Point to point",
          option_four: "Simplex",
          answer: "B",
          explaination: "Ethernet and ATM are some examples of multipoint connections",
        },
      ],

      mcq11: [
        {
          id:"11",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "When collection of various computers seems a single coherent system to its client, then it is called _________",
          option_one: "Computer Network",
          option_two: "Distributed System",
          option_three: "Networking System",
          option_four: "Mail System",
          answer: "B",
          explaination: "",
        },
      ],

      mcq12: [
        {
          id:"12",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "Two devices are in network if __________",
          option_one: "a process in one device is able to exchange information with a process in another device",
          option_two: "a process is running on both devices",
          option_three: "PIDs of the processes running of different devices are same",
          option_four: "",
          answer: "A",
          explaination: "",
        },
      ],

      mcq13: [
        {
          id:"13",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: " Which of the following computer networks is built on the top of another network?",
          option_one: "Prior Network",
          option_two: "Chief Network",
          option_three: " Prime Network",
          option_four: "Overlay Network",
          answer: "D",
          explaination: "Prior network are new type of network which solve some complex task, chief is a network of women to develop leaders ship skills, prime is FTTH network for homes. An overlay network is a virtual or logical network that is created on top of an existing physical network",
        },
      ],


      mcqx14: [
        {
          id:"14",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: " In computer network nodes are _________",
          option_one: "the computer that originates the data",
          option_two: "the computer that routes the data",
          option_three: " the computer that terminates the data",
          option_four: "all of the mentioned",
          answer: "D",
          explaination: "In a computer network, a node can be anything that is capable of sending data or receiving data or even routing the data to its destination. Routers, Computers and Smartphones are some examples of network nodes.",
        },
      ],



      mcq15: [
        {
          id:"15",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "Communication channel is shared by all the machines on the network in ________",
          option_one: "broadcast network",
          option_two: "unicast network",
          option_three: "multicast network",
          option_four: "anycast network",
          answer: "A",
          explaination: " In a broadcast network, information is sent to all stations in a network whereas in a multicast network the data or information is sent to more than one  stations but not all",
        },
      ],



      mcq16: [
        {
          id:"16",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "Bluetooth is an example of __________",
          option_one: "Personal Area Network",
          option_two: "Local Area Network",
          option_three: "Virtual Private Network",
          option_four: "Wide Area Network",
          answer: "A",
          explaination: "",
        },
      ],


      mcq17: [
        {
          id:"17",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "A __________ is a device that forwards packets between networks by processing the routing information included in the packet.",
          option_one: "Bridge ",
          option_two: "Firewall",
          option_three: "Router",
          option_four: "Hub",
          answer: "Router",
          explaination: "",
        },
      ],



      mcq18: [
        {
          id:"18",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: " A list of protocols used by a system, one protocol per layer, is called ________",
          option_one: "Protocol Architecture",
          option_two: "Protocol Stack",
          option_three: "Protocol Suite",
          option_four: "Protocol System",
          answer: "B",
          explaination: "",
        },
      ],


      mcq19: [
        {
          id:"19",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "Network congestion occurs _________",
          option_one: "In case of traffic overloading",
          option_two: "When a system terminates",
          option_three: "when connection between two nodes terminates",
          option_four: "In case of transfer failure",
          answer: "",
          explaination: "",
        },
      ],


      mcq20: [
        {
          id:"20",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "Which of the following networks extends a private network across public networks?",
          option_one: "Local Area Network",
          option_two: "Virtual Private Network ",
          option_three: "Enterprise private network",
          option_four: "Storage area network",
          answer: "B",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      mcqx: [
        {
          id:"x",
          subject_name: "cn",
          chapter_name: "Introduction",
          question: "",
          option_one: "",
          option_two: "",
          option_three: "",
          option_four: "",
          answer: "",
          explaination: "",
        },
      ],
      

  
};